# Generated by Django 6.0.5 on 2026-08-29 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_group_name', models.CharField(max_length=100, unique=True)),
                ('asset_group_description', models.TextField(default='')),
                ('asset_group_member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'asset_groups',
                'db_table': 'asset_groups',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100, unique=True)),
                ('package_description', models.TextField(default='')),
                ('package_price', models.FloatField(default=0)),
                ('package_usage', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'packages',
                'verbose_name_plural': 'packages',
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='RiskGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_group_name', models.CharField(max_length=100, unique=True)),
                ('risk_group_description', models.TextField(default='')),
                ('risk_factor', models.CharField(choices=[('LOW_RISK', 'Low Risk'), ('MODERATE', 'Moderate'), ('HIGH_RISK', 'High Risk')])),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'risk_groups',
                'verbose_name_plural': 'risk_groups',
                'db_table': 'risk_groups',
            },
        ),
        migrations.CreateModel(
            name='AcceptedAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100, unique=True)),
                ('asset_description', models.TextField(default='')),
                ('risk_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('asset_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acceptedassetgroup')),
                ('risk_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riskgroups')),
            ],
            options={
                'verbose_name': 'accepted_assets',
                'verbose_name_plural': 'accepted_assets',
                'db_table': 'accepted_assets',
            },
        ),
        migrations.AddField(
            model_name='acceptedassetgroup',
            name='risk_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riskgroups'),
        ),
    ]
