# Generated by Django 6.0.5 on 2026-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_group_name', models.CharField(max_length=100, unique=True)),
                ('asset_group_description', models.TextField(default='')),
            ],
        ),
    ]
